"""add_cancelled_to_quote_status

Revision ID: 15bf48a08be7
Revises: 2112d6fdaa51
Create Date: 2026-05-15 16:19:13.154457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15bf48a08be7'
down_revision: Union[str, Sequence[str], None] = '2112d6fdaa51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
