"""fix_critical_issues

Revision ID: 9ccb8e0175ce
Revises: bb1a119640ce
Create Date: 2026-06-23 10:54:31.468870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ccb8e0175ce'
down_revision: Union[str, Sequence[str], None] = 'bb1a119640ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'service_id', name='uq_user_service')
    )
    op.create_index(op.f('ix_favorites_service_id'), 'favorites', ['service_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.drop_index(op.f('ix_bookings_quote_id'), table_name='bookings')
    op.drop_constraint(op.f('fk_bookings_quote_id'), 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'quote_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('quote_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_bookings_quote_id'), 'bookings', 'service_quotes', ['quote_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_bookings_quote_id'), 'bookings', ['quote_id'], unique=False)
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_service_id'), table_name='favorites')
    op.drop_table('favorites')
    # ### end Alembic commands ###
