"""add_sender_id_to_notifications

Revision ID: bb1a119640ce
Revises: d0c4f1a2b3e4
Create Date: 2026-06-23 10:42:20.229544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb1a119640ce'
down_revision: Union[str, Sequence[str], None] = 'd0c4f1a2b3e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bookings_quote_id'), 'bookings', ['quote_id'], unique=False)
    op.add_column('notifications', sa.Column('sender_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_notifications_sender_id'), 'notifications', ['sender_id'], unique=False)
    op.create_foreign_key(None, 'notifications', 'users', ['sender_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_index(op.f('ix_notifications_sender_id'), table_name='notifications')
    op.drop_column('notifications', 'sender_id')
    op.drop_index(op.f('ix_bookings_quote_id'), table_name='bookings')
    # ### end Alembic commands ###
